#ifndef HEADER_GUARD_SiVAL_SiVAL_HPP
#define HEADER_GUARD_SiVAL_SiVAL_HPP

namespace SiVAL {
enum ENCLOSURE_TYPE {
    ENC_SEALED = 0,
    ENC_VENTED
};

enum DOCUMENT_TYPE {
    DT_WORKSPACE = 0,
    DT_PROJECT,
    DT_SETTINGS,
    DT_SPEAKER,
    DT_MANUFACTURER

};
}

#endif // HEADER_GUARD_SiVAL_SiVAL_HPP
