#ifndef HEADER_GUARD_SiVAL_SiVALGUI_HPP
#define HEADER_GUARD_SiVAL_SiVALGUI_HPP

namespace SiVAL {

enum PRJ_MENU {
    MENU_Project = 0,
    MENU_Speaker
};

enum DOCUMENT_TYPE {
    DT_WORKSPACE = 0,
    DT_PROJECT,
    DT_SETTINGS,
    DT_SPEAKER,
    DT_MANUFACTURER

};
}

#endif // HEADER_GUARD_SiVAL_SiVALGUI_HPP
